version: '3.9'

services:
  backend:
    image: vico958/notes-backend:latest
    container_name: notes-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: vico958/notes-frontend:latest
    container_name: notes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=backend:5000

networks:
  default:
    name: notes-app
